### ISSUE TITLE
XLib dependency

### ISSUE THREAD

**Issue by antonionehme** [XevoInc/yobd#3]
Hi,

I downloaded xlib from https://github.com/XevoInc/xlib and added the directory to yobd/include; however, I am still getting the error below. 
![Latest](https://user-images.githubusercontent.com/11300985/81085810-9a94ea80-8eef-11ea-864e-ebbe6a5c3e40.JPG)
I tried to build the project on windows 10 and ubuntu 19.04 and received the same error. Is there anything I am missing?

Thanks.

**Comment by martingkelly** [comment]
Hi, just adding the directory to `yobd/include` is not enough; you need to build and install `xlib`. You can either install it as root (`meson build .` && `sudo ninja -C build install`), or install it into a custom directory that would not require root. If you install into a custom directory, you need to set `PKG_CONFIG_PATH` to point to a directory containing a `.pc` file. If you don't know about this stuff, you may want to read a bit about `pkg-config`.

**Comment by antonionehme** [comment]
Thanks for your response.
I don't mind installing xlib as root. I am running yobd on windows. 
I pulled https://github.com/XevoInc/xlib, but this does not have a meson.build file; I think that why   `meson build . ` doesn't work. Should I modify a build file in yobd project?

**Comment by martingkelly** [comment]
Sorry, I forgot that xlib now builds with CMake (it used to use meson). So the instructions for xlib installation should be:

From the xlib directory:
```
mkdir build
cd build
cmake ..
sudo make install
```

**Comment by antonionehme** [comment]
That solved it. Many thanks!
